### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by BakitD** [BakitD/net#1]
#### TODO

 - [x] logging (change print_error, handle_error, print_message)
 - [x] add directory where files will be located for search
 - [ ] add application layer protocol - see #2 
 - [x] format code

 - server does not know how many bytes client could receive at once,
 	therefore protocol should control this value
